repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=8192]
  - id: check-merge-conflict
  - id: check-json
    exclude: tests/a-framework/parameter_file_3\.json
  - id: check-toml
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: end-of-file-fixer
    exclude: |
        (?x)(
            \.output|
            \.run_only|
            \.diff|
            ^bundled/
        )
  - id: no-commit-to-branch
    args: [--branch,master]
  - id: trailing-whitespace
    files: |
        (?x)(
            \.(cc|h$|html|doc|txt)|
            ^doc/news
        )
    exclude: ^bundled/
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.27.2
  hooks:
  - id: gitleaks
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.6
  hooks:
  - id: clang-format
    files: |
        (?x)(
            \.inst\.in |
            \.cc |
            \.h
        )$
- repo: https://github.com/crate-ci/typos
  rev: v1.33.1
  hooks:
  - id: typos
    files: (?x) ^(doc|examples|include|source|tests)/
- repo: local
  hooks:
  - id: detect-include-cycles
    name: Detect '#include' cycles
    entry: python contrib/utilities/detect_include_cycles.py
    pass_filenames: false
    language: system
