name: github-docker

on: 
  push: 
    branches: [master]

jobs:
  build-master-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker image of master 
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache_froms: dealii/dependencies:focal
          repository: dealii/dealii
          add_git_labels: true
          tags: master-focal
          path: ./contrib/docker
