name: github-docker

on:
  push:
    branches:
      - 'docker*'
      - 'master'

permissions:
  contents: read
  packages: write

jobs:
  build-master-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image of master focal
        uses: docker/build-push-action@v4
        with:
          context: ./contrib/docker/
          cache-from: type=registry,ref=dealii/dependencies:focal
          cache-to: type=inline
          build-args: |
            VER=master
            IMG=focal
          push: ${{github.ref_name == 'master'}}
          tags: dealii/dealii:master-focal

      - name: Build and push Docker image of master jammy
        uses: docker/build-push-action@v4
        with:
          context: ./contrib/docker/
          cache-from: type=registry,ref=dealii/dependencies:jammy
          cache-to: type=inline
          build-args: |
            VER=master
            IMG=jammy
          push: ${{github.ref_name == 'master'}}
          tags: dealii/dealii:master-jammy
